"""add_computation_job_history

Revision ID: 664c75220f4b
Revises: ac8ba84388c9
Create Date: 2026-01-15 12:00:00.000000

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "664c75220f4b"
down_revision = "ac8ba84388c9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted manually ###
    op.add_column("computation_jobs", sa.Column("end_time", sa.String(), nullable=True))
    op.add_column("computation_jobs", sa.Column("result", sa.String(), nullable=True))
    op.add_column("computation_jobs", sa.Column("error", sa.String(), nullable=True))
    op.add_column("computation_jobs", sa.Column("logs", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted manually ###
    op.drop_column("computation_jobs", "logs")
    op.drop_column("computation_jobs", "error")
    op.drop_column("computation_jobs", "result")
    op.drop_column("computation_jobs", "end_time")
    # ### end Alembic commands ###
